 version: '3'

 services:
   web:
    build:
        context: .
        dockerfile: ./.docker/apache2/Dockerfile
    ports:
        - '80:80'
    volumes:
        - './src:/var/www/html'
        - ./.docker/apache2/conf.d/docker-php.conf:/etc/apache2/conf-available/docker-php.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"